### ISSUE TITLE
Creative Common Licences_Version Issue

### ISSUE THREAD

**Issue by Zabandosk** [ImaginingFutures/imagining#15]
On the object detail page, creative common licences are generated in version 1.0. Auto created link is also taking the user to licence's version 1 URL. 
![image](https://github.com/ImaginingFutures/imagining/assets/71217288/738cbce5-6efd-4c44-b31f-95b30c3fff06)

We should update it to 4.0. The file we should check could be "/var/www/html/ifrepo/themes/imagining/views/Details/data/rightstatements.php"or "/var/www/html/ifrepo/themes/imagining/views/Details/ca_objects_default_html.php".

**Comment by jairomelo** [comment]
@Zabandosk Check #16 to close or continue with this issue.
