### ISSUE TITLE
Cannot create "set" for object representations

### ISSUE THREAD

**Issue by Zabandosk** [ImaginingFutures/imagining#44]
While you can create sets for objects, places, projects, you cannot create sets for object representations.
![image](https://github.com/ImaginingFutures/imagining/assets/71217288/c6f7da1a-f5cd-49f5-8bdc-4e44bd9d61f6)

You get this error:
"There was an uncaught fatal error. Please contact your system administrator and check the CollectiveAccess log files."

Same error in my local local env. Please share the solution :)

**Comment by jairomelo** [comment]
That's a normal behaviour of the platform. When you require to do bulk edits, you edit the media from the object (or any other) set.

![image](https://github.com/ImaginingFutures/imagining/assets/7632991/3b22d495-884d-4417-8c99-f2c4c1d7c933)
