### ISSUE TITLE
Merging Un/Archiving the City

### ISSUE THREAD

**Issue by jairomelo** [ImaginingFutures/imagining#50]
Dear all,

As I go thorugh the Playbook and adjust the links and titles – and respond to the emails we received from partners – I will note if I come across any discrepancies.

 

I notice there are THREE – separate Links for the Un/Archiving Beirut project

 

(Un)Archiving the City: the Case of Beirut;
http://hdl.handle.net/20.500.14542/styzvwf4n;
http://hdl.handle.net/20.500.14542/we70lvdea;
Community’s Digital Archives: Imaging the Recovery of Karantina: http://hdl.handle.net/20.500.14542/t70p7jrgz   
 

Can you pleas combine them under one file – in the same way you did for Hanadi – noting simply the different eg funding phases: Lab, Commisssion, Follow on – etc.

 

I think the title should be that of their original project:

(Un)Archiving the City: the Case of Beirut

 

I think that these can combine the two titles – or have the second title attached to one of the funding phase (I think Orhun will know what I mean in detail about this?)

 

In terms of combining the text – that may be good to include best you can together – and then get the team in Lebanon to check it – I think the ‘links’ from each of the main pages go to the same sites?

 

I would prefer if you leave in the text – the whole link or title (as they appear in this entry https://ifrepo.world/Detail/labs/75) ,

and not just the word ‘link’ which is hard to spot on first glance.

 

Hope that makes some sense.

 

Let me know WHICH link I should use for all three?

 

Thanks
Lena.

**Comment by Zabandosk** [comment]
2 projects (https://ifrepo.world/Detail/projects/9 and https://ifrepo.world/Detail/projects/12) merged under 'https://ifrepo.world/Detail/projects/9'. Other one deleted. Project and lab related to each.
