### ISSUE TITLE
Combining In Search of LA - History in the Streets

### ISSUE THREAD

**Issue by jairomelo** [ImaginingFutures/imagining#51]
And here is another one for combining (this one is not a Lab):

 

In Search of LA – History in the Streets: http://hdl.handle.net/20.500.14542/9scoc5okj
 

Currently it is under the following – but fine to combine both with the title above:

http://hdl.handle.net/20.500.14542/9scoc5okj

http://hdl.handle.net/20.500.14542/g5e8ltcsq

 

Thanks

L

**Comment by Zabandosk** [comment]
In Search of LA – History in the Streets title added. Project type added. On handle: http://hdl.handle.net/20.500.14542/9scoc5okj
Other project is deleted.
