### ISSUE TITLE
Hanadi's request

### ISSUE THREAD

**Issue by jairomelo** [ImaginingFutures/imagining#55]
Here is another request from Hanadi (Orhun you met her in Ankara I think),

 

I will also copy you all in my response to her – to the request below, but just wondered if you are happy Jake (?) to do this quick change and addition and respond to her?

 

Or what do you think would work.

 

Thanks!

L

 

 

From: Samhan, Hanadi <[hanadi.samhan.18@ucl.ac.uk](mailto:hanadi.samhan.18@ucl.ac.uk)>
Date: Friday, 22 November 2024 at 14:32
To: Isayev, Elena <[E.Isayev@exeter.ac.uk](mailto:E.Isayev@exeter.ac.uk)>, Aoife O'Leary McNeice <[aolmcn@gmail.com](mailto:aolmcn@gmail.com)>
Cc: Isayev, Elena <[E.Isayev@exeter.ac.uk](mailto:E.Isayev@exeter.ac.uk)>, Boano, Camillo <[c.boano@ucl.ac.uk](mailto:c.boano@ucl.ac.uk)>
Subject: RE: Please Check Your IF Project in the Right Place 2

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

 

Dear Elena and Aoife,

 

Thank you for sharing the project details page. I noticed that our project is currently listed twice under the following titles:

Beirut Stories
https://ifrepo.world/Detail/projects/47
Space and Violence: Thinking an Archive and Its Lifelines
https://ifrepo.world/Detail/projects/46
 

I believe it would be best to combine these entries under one unified title:
Lebanese Yawmiyat (Diaries): Archiving Unfinished Stories of Spatial Violence
Duration: 2020–2022 (Two Phases)

 

If it’s not too much trouble for your team, could you add my name ( Hanadi Samhan) to the "People of the Project" section? I’ve attached a photo for your use.

 

Thank you for your time and support. Please let me know if you need any additional information from me.

 

Best,

Hanadi

From: Isayev, Elena <[E.Isayev@exeter.ac.uk](mailto:E.Isayev@exeter.ac.uk)>
Sent: 20 November 2024 11:45
To: [e.isayev@exeter.ac.uk](mailto:e.isayev@exeter.ac.uk); Aoife O'Leary McNeice <[aolmcn@gmail.com](mailto:aolmcn@gmail.com)>
Subject: Please Check Your IF Project in the Right Place 2

 

⚠ Caution: External sender

 

It has been brought to our attention that the PDF Attachment (which is the same as the word one) – the links were not working.

 

Therefore we are re-attaching  an updated PDF  document where links work, we look forward to your response – as per the email below.

 

Warm wishes, Lena and Aoife.

 

We are writing with a request for you to check the attached Imagining Futures document in light of your project and give us any views you may have.  We need you to check if you are happy with the way your project appears (if it is listed).

 

As you will know the 4 years of the Imagining Futures Initiative have now ended, but we are continuing to publish the works which you have been contributing to, and also putting together key findings documents.

 

One of the Documents we are publishing is the attached BRIEF Overview – of ALL the projects within IF:

 

Working Title : Egalitarian Archival Practices Work Play-Book

 

On The attached Work Play-Book  Your project may appear – or not – depending on whether we felt it would be appropriate for us to list it in terms of making it public.

 

The WORD version and PDF versions – are the same (in the word one you can use the Table of Contents to move between sections)

 

Can you please check and let us know the following by 6 December 2024

(if you need more time please let us know, otherwise we will assume you are happy with it).

 

If your IF project IS listed can you please check:

Whether the Title we have included is the right one
Whether the Link we include you are happy with
If you have another link for your project you prefer us to use please provide it
Send us ONE sentence to include under the tile that sums up your project
If you prefer your project under another section – please let us know which one
 

If your project is NOT listed – and you would like it to be please let us know, and provide the information above.

 

All comments and suggestions for how to improve this document are very very welcome, please let us know if there is anything we have missed. Also if you have a proposal for a design or any Image/s or format for it – that would also be great.

 

The Work Playbook is by way of a Manifesto which will be included in the Collected Works – Online and Open Access (the ones we wrote to you about some time ago) :  https://ifrepo.world/CollectedWorks/Index

 

We look forward to hearing from you, and most importantly we hope this finds you well, and that you are able to continue with energy and creativity the important work that you have shared with us.

 

With all warm wishes, Lena and Aoife.

**Comment by Zabandosk** [comment]
projects combined under this 'http://hdl.handle.net/20.500.14542/1efh8nsro
'
