### ISSUE TITLE
Collection Map Bug

### ISSUE THREAD

**Issue by Zabandosk** [ImaginingFutures/imagining#7]
You can see the location of the object on the map even if the object is private. At least you get error when you click on it though. @jairomelo

**Comment by jairomelo** [comment]
Can you tell me a little more about that? Like if the map is in the Detail View of the Resource, Collection, Place? also if the "privacy" is associated with the origin or the destiny of the url.

**Comment by Zabandosk** [comment]
I am talking about collection page detail only. I created an object which is restricted to access in a collection. But when I go to the collection page I can see the restricted object on the map which should be restricted :D
