### ISSUE TITLE
Collection Map Text on Card

### ISSUE THREAD

**Issue by Zabandosk** [ImaginingFutures/imagining#8]
Instead of "items: title" it could be "ID:ID" and "Title: title" similar to the places detail page to keep the consistency.
![image](https://github.com/ImaginingFutures/imagining/assets/71217288/91418137-4c4d-41d2-bb96-b005997063a5)

**Comment by jairomelo** [comment]
I see. But the idea is that a single point can contains multiple resources. Therefore the logic is different.

**Comment by Zabandosk** [comment]
But still, we can add "," and add multiple objects for one point in the same format (every page) to not to break consistency and standards heuristic of [my dear Nielsen](https://www.nngroup.com/articles/ten-usability-heuristics/). Even if it is hardly possible to have multiple objects in the same point. It is only possible when there is something vertical.

**Comment by jairomelo** [comment]
In that order of ideas we can remove ID:ID and just keep a list of titles, at the end of the day is most readable. Like in places, instead of indicate coordinates the best way is to show place names. Having a list of 100 objects with Id: id, title:title is a bit unreadable.

**Comment by Zabandosk** [comment]
Yes, that make sense. I think only title would be enough.
